// Generated by CoffeeScript 1.8.0
(function() {
  var animatePage;

  animatePage = function() {
    return $('body').removeClass('before-animation');
  };

  $(function() {
    return setTimeout(animatePage, 300);
  });

}).call(this);
